<?php
$Summary1 = "<h3><strong>The MasterCard Mobile Payments Readiness Index is a data-driven, quantitative survey of the global mobile payments landscape.</strong></h3>
			<p>It gauges the readiness for mobile payments of 34 global markets, representing approximately 85 percent of the world's household consumption expenditure.</p>";
$Summary2 = "<p>Scores are derived from an algorithm comprised of over 50 inputs, including economic data, demographic data, telecommunications data, payments industry data, and proprietary consumer research. </p>
			<p>Using the Index, MasterCard has captured not only which global markets are currently most prepared to adopt mobile payments, but what remains to be done in each one moving forward. By rigorously quantifying the elements that determine mobile payments readiness, MasterCard has created a flexible, reliable methodology that advances the understanding of the future of mobile payments around the world.</p>";
$MCC = "<p><strong>Measures partnerships among banks, mobile networks, and governments.</strong> The Mobile Commerce Clusters component gauges the current state of joint ventures and affiliations among financial services organizations, telecommunications companies, and governments, and ranks their ability to work together to develop mobile payments. These partnerships are critical to the creation and commercialization of mobile payments for the countries on the Index. The more integrated an approach these entities take in developing mobile payments, the easier it is to efficiently bring products to market. The extent of partnerships among these members of the mobile payments ecosystem is a key indicator of how ready a country is for mobile payments.</p>";
$Environment = "<p><strong>Measures economic, technological, and demographic factors within a market.</strong> The Environment component quantifies variables such as household expenditure per capita, Internet usage among the population, and absorption of new technology by businesses. These demographic and economic variables affect a market's readiness for mobile payments. A market with high Internet usage and businesses that readily adapt to and incorporate new technologies into their operations creates an environment that is conducive to mobile payments. This is especially true in the case of point-of-sale (POS) payments, where new technology adoption by retailers is critical to their success. But it is also true for m-commerce (for example, .mobi pages and mobile check out) and person-to-person (P2P) payments, where mobile devices become the acceptance media at POS. These broad metrics are good proxies for measuring the extent to which mobile may grow in a given market in the mid-term.</p>";
$Infrastructure = "<p><strong>Measures the sophistication and penetration of the mobile phone industry and NFC terminalization.</strong> The Infrastructure component calibrates the impact of variables such as mobile phone penetration, network coverage, and NFC terminalization levels that help determine mobile payments readiness. Low mobile phone penetration and network coverage place a ceiling on how fast mobile payments can develop and the extent to which consumers can take advantage of them in a broad-based way. Low NFC terminalization inhibits the use of NFC payments at the point of sale. Healthy scores on these factors are critical to mobile payments development and provide convenient markers today that indicate gaps to span tomorrow.   </p>";
$Readiness = "<p><strong>Measures how familiar with, how willing to use, and how frequently consumers are currently using all three types of mobile payments.</strong> The Consumer Readiness component determines consumers' knowledge of, comfort with, and experience using person-to-person, point-of-sale, and m-commerce payments. Consumer readiness is a necessary condition for mobile payments to develop; even the most favorable market forces cannot compensate for the lack of consumer readiness. By surveying consumers in all 34 countries and quantifying their familiarity with, willingness to use, and current usage of mobile payments; the Index provides proof points that can guide industry players who are looking to build public demand and usage of mobile payments and organize the different types of mobile payments into short, medium, and long-term opportunities. This metric differentiates the MasterCard Index from other gauges of mobile payments readiness, which focus exclusively on the technological components.</p>";
$Financial = "<p><strong>Measures the effectiveness and penetration of consumer financial products.</strong> The Financial component measures market-specific variables such as accessibility to financial services, new technology usage, and how well the banking system serves consumers. The reach and resilience of the financial services industry is key to the development of many types of mobile payments. Markets that have well-developed financial services industries, which consumers can easily access and habitually trust, are better positioned to develop mobile payments offerings that consumers will value and use. The absence of a secure, sound, and accessible banking system may, in some cases, actually foster the growth of one kind of mobile payments (P2P), but it precludes a broad rollout across all three varieties.</p>";
$Regulations = "<p><strong>Measures legal and regulatory structures and how they affect businesses.</strong> The Regulation component assesses variables based on the efficiency of legal and regulatory systems in resolving disputes, regulating industry, and developing laws for information and communication technology, as well as protecting financial assets and intellectual property. Countries that have legal systems that are effective in settling disputes and regulating industry, and offer well-developed legal codes for the information and communication industries, provide regulatory frameworks that foster the development of mobile payments. With so many interconnected parties developing mobile payments, having trust in regulatory bodies and an efficient and cost-effective forum for settling disputes will promote more of the partnerships that are critical to the success of mobile payments.
</p>";
$DataSources = "<li><a href='http://www.un.org/esa/population/'><i>United Nations</i></a> (2011)</li>
				<li><a href='http://www.census.gov/'><i>US Census Bureau</i></a> (2011)</li>
				<li><a href='http://data.worldbank.org/indicator'><i>World Bank World Development Indicators</i></a> (2010)</li>
				<li><a href='http://www.imf.org/external/data.htm'><i>International Monetary Fund International Financial Statistics</i></a> (2010)</li>
				<li><a href='http://www.itu.int/ITU-D/ict/index.html'><i>International Telecommunications Union</i></a> (2010)</li>
				<li><a href='http://www.weforum.org/issues/global-information-technology'><i>World Economic Forum Global Information Technology Report</i></a> (2011)</li>
				<li><a href='http://www.weforum.org/issues/global-competitiveness'><i>World Economic Form Global Competitiveness Report</i></a> (2011)</li>
				<li><a href='http://www.euromonitor.com/'><i>Euromonitor International</i></a> (2010)</li>
				<li><a href='http://econ.worldbank.org/WBSITE/EXTERNAL/DATASTATISTICS/0,,contentMDK:20487483~isCURL:Y~menuPK:1192714~pagePK:64133150~piPK:64133175~theSitePK:239419,00.html'><i>The World Bank Information and Communications for Development Online Database</i></a> (2011)</li>
				<li><a href='https://www.cia.gov/library/publications/the-world-factbook/index.html'><i>CIA World Factbook</i></a> (2012)</li>
				<li><i>Proprietary Consumer Research for MasterCard Worldwide</i> (2011)</li>";
?>
