<?php
$OverallIndexScore = "33.2";
$ConsumerReadinessScore = "12.4";
$MobileCommerceClusterScore = "19.1";
$EnvironmentScore = "52.8";
$FinancialServicesScore = "63.1";
$InfrastructureScore = "34.5";
$RegulationsScore = "62.8";
$FamiliarityAverage = 15.8;
$FamiliarityHigh = 52.1; /* 53.3; */
$FamiliarityLeader = "Kenya";
$FamiliarityAverageP2P = 16.4;
$FamiliarityHighP2P = 88.6;
$FamiliarityLeaderP2P = "Kenya";
$FamiliarityAveragePOS = 11.3;
$FamiliarityHighPOS = 30; /* 31.4; */
$FamiliarityLeaderPOS = "Kenya";
$FamiliarityAverageMCOMM = 19.5;
$FamiliarityHighMCOMM = 41; /* 42.0; */
$FamiliarityLeaderMCOMM = "United States";
$WillingnessAverage = 18.8;
$WillingnessHigh = 59.9; /* 61.2; */
$WillingnessLeader = "Nigeria";
$WillingnessAverageP2P = 18.9;
$WillingnessHighP2P = 88; /* 88.8; */
$WillingnessLeaderP2P = "Kenya";
$WillingnessAveragePOS = 16.7;
$WillingnessHighPOS = 55; /* 56.0; */
$WillingnessLeaderPOS = "Nigeria";
$WillingnessAverageMCOMM = 20.7;
$WillingnessHighMCOMM = 58; /* 59.1; */
$WillingnessLeaderMCOMM = "Nigeria";
$FrequencyAverage = 7.5;
$FrequencyHigh = 29.9; /* 31; */
$FrequencyLeader = "Kenya";
$FrequencyAverageP2P = 8.1;
$FrequencyHighP2P = 66.9; /* 67.9; */
$FrequencyLeaderP2P = "Kenya";
$FrequencyAveragePOS = 5.0;
$FrequencyHighPOS = 14; /* 15.0; */
$FrequencyLeaderPOS = "Saudi Arabia";
$FrequencyAverageMCOMM = 9.4;
$FrequencyHighMCOMM = 25.1; /* 26.0; */
$FrequencyLeaderMCOMM = "Saudi Arabia";
?>